// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyMvcApp.Data;
using MyMvcApp.Models;

#nullable disable

namespace MyMvcApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 255);

            
            modelBuilder.Entity("MyMvcApp.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<bool>("IsOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_online");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_reset_token");

                    b.Property<DateTime?>("PasswordResetTokenExpires")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("password_reset_token_expires");

                    b.Property<string>("RequestStatus")
                        .IsRequired()
                        .HasMaxLength(0)
                        .HasColumnType("longtext")
                        .HasColumnName("request_status");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(0)
                        .HasColumnType("longtext")
                        .HasColumnName("roles");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("username");

                    b.HasKey("AccountId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("uq_accounts_userename");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("MyMvcApp.Models.AcademicProfile", b =>
                {
                    b.Property<int>("AcademicProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("academic_profile_id");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<string>("Section")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("section");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<string>("AcademicStatus")
                        .IsRequired()
                        .HasMaxLength(0)
                        .HasColumnType("longtext")
                        .HasColumnName("academic_status");

                    b.HasKey("AcademicProfileId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId")
                        .IsUnique()
                        .HasDatabaseName("uq_academic_profile_student_id");

                    b.ToTable("AcademicProfiles");
                });

            modelBuilder.Entity("MyMvcApp.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("course_code");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.HasKey("CourseId");

                    b.HasIndex("CourseCode")
                        .IsUnique()
                        .HasDatabaseName("uq_courses_course_code");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("MyMvcApp.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<string>("Firstname")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("firstname");

                    b.Property<string>("Lastname")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("lastname");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("middle_name");

                    b.HasKey("StudentId");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("uq_students_account_id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("MyMvcApp.Models.AcademicProfile", b =>
                {
                    b.HasOne("MyMvcApp.Models.Course", "Course")
                        .WithMany("AcademicProfiles")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyMvcApp.Models.Student", "Student")
                        .WithOne("AcademicProfile")
                        .HasForeignKey("MyMvcApp.Models.AcademicProfile", "StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MyMvcApp.Models.Student", b =>
                {
                    b.HasOne("MyMvcApp.Models.Account", "Account")
                        .WithOne("Student")
                        .HasForeignKey("MyMvcApp.Models.Student", "AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MyMvcApp.Models.Course", b =>
                {
                    b.Navigation("AcademicProfiles");
                });

            modelBuilder.Entity("MyMvcApp.Models.Account", b =>
                {
                    b.Navigation("Student");
                });

            modelBuilder.Entity("MyMvcApp.Models.Student", b =>
                {
                    b.Navigation("AcademicProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
